### ISSUE TITLE
Clickhouse-Kafka-Connect have less through put

### ISSUE THREAD

**Issue by amolsr** [ClickHouse/clickhouse-kafka-connect#487]
**Is your feature request related to a problem? Please describe.**
We need to build a dimension table for a ClickHouse dataset that undergoes frequent updates. However, the current throughput is limited to approximately 300-500 messages per second, which is significantly lower than the recommended batch insertion guidelines of 10,000 to 100,000 rows. This low throughput is a bottleneck for maintaining the table efficiently.

**Describe the solution you'd like**
Develop a native TCP/IP-based connector optimized for high-throughput data ingestion into ClickHouse. This connector should leverage ClickHouse's native protocol to efficiently batch and insert large volumes of data, enabling adherence to the recommended batch sizes and significantly improving performance.

**Comment by amolsr** [comment]
Yeah I have tried using the setting you have mentioned. Still, the through put is very less.

**Comment by amolsr** [comment]
I used https://housepower.github.io/ClickHouse-Native-JDBC/ driver to achieve high throughput as majority of click-house driver is very slow.

**Comment by amolsr** [comment]
Answering to your question : 

Roughly how many messages are you looking to send - in a batch of 10,000 to 1 lakh
Roughly how big is each message  about 1 kb
How many partitions does the topic have? 1 as increasing partition will decrease the clickhouse performance. 
What format is the data in? (e.g. Avro, Protobuf, JSON, etc...) json

We are using batching for insertion in clickhouse.

**Comment by amolsr** [comment]
I tried with the single line only. Still no effect on the throughput. We tried with multiple partitions as well, but that did't worked as well. Should we connect on this offline .?

**Comment by amolsr** [comment]
Clickhouse connector Infomation
```
{
   "name": "clickhouse-connect",
   "config": {
       "connector.class": "com.clickhouse.kafka.connect.ClickHouseSinkConnector",
       "tasks.max": "50",
       "consumer.override.max.poll.records": "10000",
       "consumer.override.max.partition.fetch.bytes": "10485760",
       "database": "ad_hoc",
       "errors.retry.timeout": "60",
       "exactlyOnce": "false",
       "hostname": "10.120.11.147",
       "port": "8123",
       "username": "******",
       "password": "******",
       "topics": "cdc.****",
       "value.converter": "org.apache.kafka.connect.json.JsonConverter",
       "value.converter.schemas.enable": "true",
       "clickhouseSettings": "",
       "transforms": "flatten",
       "transforms.flatten.type": "org.apache.kafka.connect.transforms.Flatten$Value",
       "transforms.flatten.delimiter": "_",
       "errors.tolerance": "all",
       "errors.deadletterqueue.topic.name": "cdc.****"
   }
}

```

My SQL Connector Configuration

```
{
   "name": "Staging-mysql-connect",
   "config": {
       "connector.class": "io.debezium.connector.mysql.MySqlConnector",
       "topic.prefix": "cdc",
       "database.user": "********",
       "snapshot.mode": "never",
       "schema.history.internal.kafka.topic": "cdc.history",
       "database.server.id": "1",
       "database.hostname": "***********",
       "database.password": "*********",
       "schema.history.internal.kafka.bootstrap.servers": "*******:9094",
       "table.include.list": "cdc.Users",
       "database.include.list": "cdc",
       "column.exclude.list": cdc.Users.phone,phone",
       "skip.messages.without.change": "true"
   }
}

```

These are the configuration we are using.

**Comment by amolsr** [comment]
We are using Jmeter Setup for performance bench marking.

**Comment by amolnaukri** [comment]
awaiting resolution.

**Comment by amolnaukri** [comment]
The table is horizontally scaled, and I want to know whether this connector uses an HTTP-based driver or a TCP/IP-based driver. If it uses an HTTP-based driver, could you list the current limitations for this driver?

**Comment by amolsr** [comment]
Also Do we have plan to use the 9000 port to interact with the clickhouse server. As, TCP port can offer higher throughput. Thanks.

**Comment by ne1r0n** [comment]
@amolsr try to add the following to your ClickHouse connector config:
```
"connector.client.config.override.policy"     : "All",
```

Also you can try to set higher max.wait, for example 1 sec:
```
"consumer.override.fetch.max.wait.ms"         : 1000
```

**Comment by amolsr** [comment]
It does not work.

**Comment by captainpro-eng** [comment]
@amolsr it is resolved?

**Comment by amolnaukri** [comment]
Still not. I see there is potential to increase the through put if the underlying driver is replaced. Lets collaborate on that if you are interested.
